### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by afang** [ebidel/polymer-gmail#11]
![](http://puu.sh/mCC8M/eee29c3b96.png)

**Comment by ebidel** [comment]
Hmm, I don't see that same error if I hard refresh (with and without service worker).

**Comment by afang** [comment]
I just installed again and got the same errors: 

![](http://puu.sh/mCXUD/60eb94cdbf.png)

There're no errors on the server though.

**Comment by ebidel** [comment]
Ah so you're running locally? You need to follow the build/run instructions: https://github.com/ebidel/polymer-gmail#development--building

**Comment by afang** [comment]
I'm still getting the same error ![](http://puu.sh/mCZcB/81db44c7a3.png)

I cloned the repo, ran `npm install`, `gulp jsbundle`, and `serve -p 8080`

**Comment by ebidel** [comment]
Ah, sorry. You need to run `gulp`, serve the root, and hit `/dist`: localhost:8080/dist/

Updated the readme to reflect that:
https://github.com/ebidel/polymer-gmail/blob/master/README.md#run-the-app
