### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by davehorton** [ebidel/polymer-gmail#14]
Not sure if this is something about my environment, but 'bower install' (whether called directly, or via npm install) does not create a bower components directory, and I cannot make sense of the warning:

```
$ npm install
npm WARN prefer global jshint@2.9.2 should be installed with -g

> polymail@0.1.16 postinstall /Users/dhorton/beachdog-enterprises/beachdog-networks/git/polymer-gmail
> bower install

[{
  "level": "warn",
  "id": "invalid-meta",
  "message": "The \"name\" is recommended to be lowercase, can contain digits, dots, dashes",
  "data": {}
}]
{}

$ node --version
v6.2.2
$ npm --version
3.9.5
```

**Comment by ebidel** [comment]
This worked for me:

```
ericbidelman-macbookpro3:polymer-gmail ericbidelman$ npm -v
3.10.3
ericbidelman-macbookpro3:polymer-gmail ericbidelman$ node -v
v6.3.0
ericbidelman-macbookpro3:polymer-gmail ericbidelman$ bower -v
1.7.9
ericbidelman-macbookpro3:polymer-gmail ericbidelman$ 
```

**Comment by davehorton** [comment]
The warning seems to be because bower does not like uppercase letters in the 'name' field in bower.json for some reason (https://github.com/bower/spec/blob/master/json.md#name).

However, regardless of the warning (even if I change the name to 'polymer-mail') I still don't get a bower_components folder.

Interestingly, I am using the same versions as you at this point:

```
MacBook-Pro-3:polymer-gmail dhorton$ npm -v
3.10.3
MacBook-Pro-3:polymer-gmail dhorton$ node -v
v6.3.0
MacBook-Pro-3:polymer-gmail dhorton$ bower -v
1.7.9
MacBook-Pro-3:polymer-gmail dhorton$ bower install
{}
```

**Comment by davehorton** [comment]
I solved it by creating a simple .bowerrc in the project directory:

```
{
        "directory": "bower_components"
}
```
