### ISSUE TITLE
gulp on fresh install complains ' Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by davehorton** [ebidel/polymer-gmail#15]
I manually installed them, but perhaps they should be added to devDependencies in package.json?

```
$ npm install --save-dev jshint gulp-jshint
```

**Comment by ebidel** [comment]
Should already be taken care of: https://github.com/ebidel/polymer-gmail/blob/master/package.json#L24

**Comment by davehorton** [comment]
Yes, I guess my problem was that I did not have jshint globally installed.
