### ISSUE TITLE
Accessibility...

### ISSUE THREAD

**Issue by patrickhlauke** [ebidel/polymer-gmail#2]
Google has expertise in-house to create functional, beautiful, web-component stuff that is also accessible. It would be great if high-profile demos like these would actually take advantage of those resources to create things that work not just for sighted mouse/touchscreen users...

**Comment by jerryf196** [comment]
Polymer is an interest for me. Haven't done any polymer development yet but will in the near future. Of course this project is a good starting point. I tested this example on my samsung 3 mini and everything is slow. From scroll events to touch events. I guess more performance development is needed?

**Comment by rizvan** [comment]
Must say a best start , would love to work with you on this project . Will learn new things and implement .
