### ISSUE TITLE
Vulcanized not found

### ISSUE THREAD

**Issue by bruunofco** [ebidel/polymer-gmail#3]
Hello,

I'm new to polymer and am unable to start the application, it is not being finding the file 'polymer-gmail-master / vulcanized.html Failed to load resource: the server responded with a status of 404 (Not Found)' '

What does this file? where I find?

**Comment by ragingwind** [comment]
You should use vulcanize the elements to make `vulcanized.html` before run web server. after install bower packages and then run this command. 

`vulcanize elements.html`

and refer to this articles to understand `vulcanize`: [Concatenating Web Components with Vulcanize - Polymer](http://goo.gl/4T8kjw)
