### ISSUE TITLE
I get ENOENT error when i Vulcanize

### ISSUE THREAD

**Issue by devAtPolydeals** [ebidel/polymer-gmail#7]
Any idea why this would be happening? The error is:
   
    C:\wamp\www\polymerApps\gmail1.0\elements>vulcanize -o vulcanized.html elements.html
     { [Error: ENOENT, open 'C:\wamp\www\polymerApps\gmail1.0\elements\vulcanized.html']
       errno: -4058,
       code: 'ENOENT',
       path: 'C:\\wamp\\www\\polymerApps\\gmail1.0\\elements\\vulcanized.html' }
     Error: ENOENT, open 'C:\wamp\www\polymerApps\gmail1.0\elements\vulcanized.html'
         at Error (native)

**Comment by ebidel** [comment]
I updated the README instructions to run vulcanize through gulp. Can you give that a try?

**Comment by devAtPolydeals** [comment]
Everything went smooth.

FYI serve -p 8080 did not work for me, i don't use npm serve so not an issue for me.
