### ISSUE TITLE
Polymer V1 app does not work in Firefox

### ISSUE THREAD

**Issue by devAtPolydeals** [ebidel/polymer-gmail#8]
The new version of https://poly-mail.appspot.com/ is not working with Firefox latest version (39). It cannot process https://github.com/ebidel/polymer-gmail/blob/1.0/scripts/app.js#L86-L90. May be firefox does not support ```link.import``` OR ```link.import.readyState``` ??

CC: @ebidel

**Comment by ebidel** [comment]
Hmm, the live site works fine for me in 39. Be sure you don't have the webcomponents flag on in about:config. 

FF should hit https://github.com/ebidel/polymer-gmail/blob/1.0/scripts/app.js#L89 because `link.import` will fail. Same with Safari.

**Comment by devAtPolydeals** [comment]
Yes, you are right it was the flag.

**Comment by devAtPolydeals** [comment]
The gmail app works in firefox but when i use the code in my app it doesnt work (in firefox), it fails here https://github.com/ebidel/polymer-gmail/blob/1.0/scripts/app.js#L71 and says:

app.render() is not a function
I added try catch like below and it now works fine.

```
	try{
		app.render();
	}
	catch(err){
		console.log("app.render() fails in this browser");
	}
```
